/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperRouteImport } from './routes/super'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangeEmailRouteImport } from './routes/change-email'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as ApiPublicBootstrapRouteImport } from './routes/api/public/bootstrap'
import { Route as ApiAdminResetPasswordRouteImport } from './routes/api/admin/reset-password'
import { Route as ApiAdminCreateRouteImport } from './routes/api/admin/create'
import { Route as ApiAccountForgotIdRouteImport } from './routes/api/account/forgot-id'
import { Route as ApiAccountChangeEmailRouteImport } from './routes/api/account/change-email'

const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeEmailRoute = ChangeEmailRouteImport.update({
  id: '/change-email',
  path: '/change-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapRoute = ApiPublicBootstrapRouteImport.update({
  id: '/api/public/bootstrap',
  path: '/api/public/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResetPasswordRoute = ApiAdminResetPasswordRouteImport.update({
  id: '/api/admin/reset-password',
  path: '/api/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCreateRoute = ApiAdminCreateRouteImport.update({
  id: '/api/admin/create',
  path: '/api/admin/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountForgotIdRoute = ApiAccountForgotIdRouteImport.update({
  id: '/api/account/forgot-id',
  path: '/api/account/forgot-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountChangeEmailRoute = ApiAccountChangeEmailRouteImport.update({
  id: '/api/account/change-email',
  path: '/api/account/change-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/analytics': typeof AnalyticsRoute
  '/change-email': typeof ChangeEmailRoute
  '/dashboard': typeof DashboardRoute
  '/enroll': typeof EnrollRoute
  '/login': typeof LoginRoute
  '/super': typeof SuperRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/api/account/change-email': typeof ApiAccountChangeEmailRoute
  '/api/account/forgot-id': typeof ApiAccountForgotIdRoute
  '/api/admin/create': typeof ApiAdminCreateRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/analytics': typeof AnalyticsRoute
  '/change-email': typeof ChangeEmailRoute
  '/dashboard': typeof DashboardRoute
  '/enroll': typeof EnrollRoute
  '/login': typeof LoginRoute
  '/super': typeof SuperRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/api/account/change-email': typeof ApiAccountChangeEmailRoute
  '/api/account/forgot-id': typeof ApiAccountForgotIdRoute
  '/api/admin/create': typeof ApiAdminCreateRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admins': typeof AdminsRoute
  '/analytics': typeof AnalyticsRoute
  '/change-email': typeof ChangeEmailRoute
  '/dashboard': typeof DashboardRoute
  '/enroll': typeof EnrollRoute
  '/login': typeof LoginRoute
  '/super': typeof SuperRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/api/account/change-email': typeof ApiAccountChangeEmailRoute
  '/api/account/forgot-id': typeof ApiAccountForgotIdRoute
  '/api/admin/create': typeof ApiAdminCreateRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admins'
    | '/analytics'
    | '/change-email'
    | '/dashboard'
    | '/enroll'
    | '/login'
    | '/super'
    | '/receipt/$id'
    | '/api/account/change-email'
    | '/api/account/forgot-id'
    | '/api/admin/create'
    | '/api/admin/reset-password'
    | '/api/public/bootstrap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/analytics'
    | '/change-email'
    | '/dashboard'
    | '/enroll'
    | '/login'
    | '/super'
    | '/receipt/$id'
    | '/api/account/change-email'
    | '/api/account/forgot-id'
    | '/api/admin/create'
    | '/api/admin/reset-password'
    | '/api/public/bootstrap'
  id:
    | '__root__'
    | '/'
    | '/admins'
    | '/analytics'
    | '/change-email'
    | '/dashboard'
    | '/enroll'
    | '/login'
    | '/super'
    | '/receipt/$id'
    | '/api/account/change-email'
    | '/api/account/forgot-id'
    | '/api/admin/create'
    | '/api/admin/reset-password'
    | '/api/public/bootstrap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminsRoute: typeof AdminsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ChangeEmailRoute: typeof ChangeEmailRoute
  DashboardRoute: typeof DashboardRoute
  EnrollRoute: typeof EnrollRoute
  LoginRoute: typeof LoginRoute
  SuperRoute: typeof SuperRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
  ApiAccountChangeEmailRoute: typeof ApiAccountChangeEmailRoute
  ApiAccountForgotIdRoute: typeof ApiAccountForgotIdRoute
  ApiAdminCreateRoute: typeof ApiAdminCreateRoute
  ApiAdminResetPasswordRoute: typeof ApiAdminResetPasswordRoute
  ApiPublicBootstrapRoute: typeof ApiPublicBootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-email': {
      id: '/change-email'
      path: '/change-email'
      fullPath: '/change-email'
      preLoaderRoute: typeof ChangeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap': {
      id: '/api/public/bootstrap'
      path: '/api/public/bootstrap'
      fullPath: '/api/public/bootstrap'
      preLoaderRoute: typeof ApiPublicBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reset-password': {
      id: '/api/admin/reset-password'
      path: '/api/admin/reset-password'
      fullPath: '/api/admin/reset-password'
      preLoaderRoute: typeof ApiAdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/create': {
      id: '/api/admin/create'
      path: '/api/admin/create'
      fullPath: '/api/admin/create'
      preLoaderRoute: typeof ApiAdminCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/forgot-id': {
      id: '/api/account/forgot-id'
      path: '/api/account/forgot-id'
      fullPath: '/api/account/forgot-id'
      preLoaderRoute: typeof ApiAccountForgotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/change-email': {
      id: '/api/account/change-email'
      path: '/api/account/change-email'
      fullPath: '/api/account/change-email'
      preLoaderRoute: typeof ApiAccountChangeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminsRoute: AdminsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ChangeEmailRoute: ChangeEmailRoute,
  DashboardRoute: DashboardRoute,
  EnrollRoute: EnrollRoute,
  LoginRoute: LoginRoute,
  SuperRoute: SuperRoute,
  ReceiptIdRoute: ReceiptIdRoute,
  ApiAccountChangeEmailRoute: ApiAccountChangeEmailRoute,
  ApiAccountForgotIdRoute: ApiAccountForgotIdRoute,
  ApiAdminCreateRoute: ApiAdminCreateRoute,
  ApiAdminResetPasswordRoute: ApiAdminResetPasswordRoute,
  ApiPublicBootstrapRoute: ApiPublicBootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
