/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBootstrapRouteImport } from './routes/api/public/bootstrap'
import { Route as ApiAdminResetPasswordRouteImport } from './routes/api/admin/reset-password'
import { Route as ApiAdminCreateRouteImport } from './routes/api/admin/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapRoute = ApiPublicBootstrapRouteImport.update({
  id: '/api/public/bootstrap',
  path: '/api/public/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResetPasswordRoute = ApiAdminResetPasswordRouteImport.update({
  id: '/api/admin/reset-password',
  path: '/api/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCreateRoute = ApiAdminCreateRouteImport.update({
  id: '/api/admin/create',
  path: '/api/admin/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/admin/create': typeof ApiAdminCreateRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/admin/create': typeof ApiAdminCreateRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/admin/create': typeof ApiAdminCreateRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/admin/create'
    | '/api/admin/reset-password'
    | '/api/public/bootstrap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/admin/create'
    | '/api/admin/reset-password'
    | '/api/public/bootstrap'
  id:
    | '__root__'
    | '/'
    | '/api/admin/create'
    | '/api/admin/reset-password'
    | '/api/public/bootstrap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAdminCreateRoute: typeof ApiAdminCreateRoute
  ApiAdminResetPasswordRoute: typeof ApiAdminResetPasswordRoute
  ApiPublicBootstrapRoute: typeof ApiPublicBootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap': {
      id: '/api/public/bootstrap'
      path: '/api/public/bootstrap'
      fullPath: '/api/public/bootstrap'
      preLoaderRoute: typeof ApiPublicBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reset-password': {
      id: '/api/admin/reset-password'
      path: '/api/admin/reset-password'
      fullPath: '/api/admin/reset-password'
      preLoaderRoute: typeof ApiAdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/create': {
      id: '/api/admin/create'
      path: '/api/admin/create'
      fullPath: '/api/admin/create'
      preLoaderRoute: typeof ApiAdminCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAdminCreateRoute: ApiAdminCreateRoute,
  ApiAdminResetPasswordRoute: ApiAdminResetPasswordRoute,
  ApiPublicBootstrapRoute: ApiPublicBootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
